namespace learncsharp;

public record RPersonMutable
{
    public string? Name { get; set; }
    public int? Age { get; init; }
    public DateTime? HireDate { get; set; }

    public RPersonMutable(string name, int age, DateTime hireDate)
    {
        this.Name = name;
        this.Age = age;
        this.HireDate = hireDate;
    }
}

public record RPersonImmutable (string Name, int Age, DateOnly HireDate);

public class BasicFeatures
{
    public BasicFeatures()
    {
        // Default constructor
    }

    public void DemonstrateRecords()
    {
        // Immutable Record (cannot be changed after creation)
        RPersonImmutable person1 = new RPersonImmutable("Tony", 54, DateOnly.FromDateTime(DateTime.Now));
        Console.WriteLine($"person1: {person1.Name}, {person1.Age}, {person1.HireDate}");

        // Mutable Record (can be changed after creation), except Age which is init-only
        RPersonMutable person2 = new RPersonMutable("Jane", 30, DateTime.Now);
        Console.WriteLine($"person2: {person2.Name}, {person2.Age}, {person2.HireDate}");
        person2.Name = "Paula";
        person2.HireDate = DateTime.Now.AddYears(-1);
        Console.WriteLine($"person2 (after changes): {person2.Name}, {person2.Age}, {person2.HireDate}");
    }

    // Function  automatically generated by GitHub copilot after entering "public void FizzBuzz()"
    public void FizzBuzz()
    {
        // Example FizzBuzz implementation
        for (int i = 1; i <= 100; i++)
        {
            if (i % 15 == 0)
                Console.WriteLine("FizzBuzz");
            else if (i % 3 == 0)
                Console.WriteLine("Fizz");
            else if (i % 5 == 0)
                Console.WriteLine("Buzz");
            else
                Console.WriteLine(i);
        }
    }

    // Create a function to add array of integers (copilot prompt to create this function)
    public int AddArray(int[] numbers)
    {
        int sum = 0;
        foreach (int number in numbers)
        {
            sum += number;
        }
        return sum;
    }

}
